name: .NET Core CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Get Files
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build and Pack Library with .NET Core
      run: .\Build.ps1
    # - name: Setup Nuget.exe
    #  uses: warrenbuckley/Setup-Nuget@v1
    # - name: Add GitHub Packages Source to Nuget.exe
    #  run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/FluxpointDev/index.json" -UserName FluxpointDev -Password ${{ secrets.GITHUBTOKEN }}
    # - name: Push Library to Github Packages
    #  run: |
    #    cd ./src/Fluxup.Updater/bin/Release
    #    nuget push *.nupkg -Source "GitHub"
